[platformio]
default_envs = slave

[env]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.arduino.memory_type = qio_opi
board_build.partitions = default_16MB.csv
build_flags =
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DCORE_DEBUG_LEVEL=3
lib_deps =
  jgromes/RadioLib@^7.1.2
  mikalhart/TinyGPSPlus@^1.1.0
  bblanchon/ArduinoJson@^7.3.0

[env:slave]
build_flags =
  ${env.build_flags}
  -DROLE_SLAVE=1
src_filter =
  +<common/>
  +<slave/>

[env:gateway]
build_flags =
  ${env.build_flags}
  -DROLE_GATEWAY=1
src_filter =
  +<common/>
  +<gateway/>
